user_name = input('input user name:')
student_id = input('input user ID:')
score_Chinese = int(input('input score of Chinese: '))
score_Intro_CS = int(input('input score of Introduction of Computer: '))
score_Pg_Design = int(input('input score of Programming Design: '))
print('Name:'+user_name)
print('ID:' + student_id)
print('Average:'+ str(int((score_Chinese+score_Intro_CS+score_Pg_Design)/3)))
print('Total:'+ str(score_Chinese+score_Intro_CS+score_Pg_Design))