import numpy as np
a=np.arange(0,24).reshape((2,3,4))
print('a(2,3,4)=\n',a)
print('\na[0,1,1]=\n',a[0,1,1])
print('\na[:,2]=\n',a[:,2])
print('\na[:,:,1]=\n',a[:,:,1])
print('\na[::2,::2,::1]=\n',a[::2,::2,::1])
print('\nones((2,3))=\n',np.ones((2,3)))
print('\nzeros((3,2))=\n',np.zeros((3,2)))
print('\nfull((3,3),-1)=\n',np.full((3,3),-1))
b = np.arange(9).reshape((3,3))
print('\nb(3,3)=\n',b)
print('\nTotal sum of b =', b.sum())
print('\nbyCol: b.sum( axis=0 ) =', b.sum(axis=0))
print('\nbyRow: b.sum( axis=1 ) =', b.sum(axis=1))
print('\nRow sum of b[0] =', b[0].sum())
print('\nColumn sum of b[:, 0] =', b[:,0].sum())
print('\n1.value count by np.count_nonzero:', np.count_nonzero(b==0))
print('\n2.value count by sum():', (b==0).sum())